In [1]:
#!pip install numpy

In [2]:
#!pip install pandas

In [3]:
#!pip list

In [4]:
#!pip install ipykernel

In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
df_1=pd.read_csv('Enron.csv')
df_1.head(25)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0


In [8]:
df_2=pd.read_csv('Ling.csv')
df_2.head(25)

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
5,call for abstracts : optimality in syntactic t...,content - length : 4437 call for papers is the...,0
6,m . a . in scandinavian linguistics,m . a . in scandinavian linguistics at the uni...,0
7,call for papers : linguistics session of the m...,call for papers linguistics session - - midwes...,0
8,foreign language in commercials,content - length : 1937 greetings ! i ' m wond...,0
9,fulbright announcement : please post / dissemi...,fulbright announcement : please post / dissemi...,0


In [9]:
print(df_1.shape)

(29767, 3)


In [10]:
df_1.head()


,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0


In [11]:
df_1.tail()

,subject,body,label
29762,confidence is back,"hello ,\r\nmy boyfriend began having problems ...",1
29763,important information,love - potion for your darling is all you want...,1
29764,vys - make itnger,you have feelings of guilt and embarrassment ...,1
29765,the best thing come in large parcels,spur - m formula\r\nincrease sperm production ...,1
29766,it works amaziing,"hello , welcome to the medzonlin claiming e\r\...",1


In [12]:
print(df_2.shape)

(2859, 3)


In [13]:
df_2.head()

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0


In [14]:
df_2.tail()

,subject,body,label
2854,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
2855,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
2856,anglicization of composers ' names,"judging from the return post , i must have sou...",0
2857,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
2858,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0


In [15]:
# merge two dataframes df_1 & df_2
df_merge= pd.concat([df_1, df_2], ignore_index=True)


In [16]:
print(df_merge.shape)

(32626, 3)


In [17]:
df_merge.head(50)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0


In [18]:
df_merge.tail()

,subject,body,label
32621,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
32622,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
32623,anglicization of composers ' names,"judging from the return post , i must have sou...",0
32624,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
32625,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0


In [19]:
df_merge.to_csv("output.csv", index=False)

In [20]:
df_merge["label"].value_counts()

label
0    18192
1    14434
Name: count, dtype: int64

In [21]:
!pip install nltk


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
#def preprocess(text):
    # 1. lowercase
    #text = text.lower()
    
    # 2. remove punctuation
    #import string
    #text = ''.join(c for c in text if c not in string.punctuation)
    
    # 3. tokenize
    #from nltk import word_tokenize
    #words = word_tokenize(text)
    
    # 4. POS tagging
    #from nltk import pos_tag
    #tagged = pos_tag(words)
    
    # 5. lemmatization
    #from nltk.stem import WordNetLemmatizer
    #from nltk.corpus import wordnet
    
    #def get_wordnet_pos(tag):
        #if tag.startswith('J'):
            #return wordnet.ADJ
        #elif tag.startswith('V'):
            #return wordnet.VERB
        #elif tag.startswith('N'):
            #return wordnet.NOUN
        #elif tag.startswith('R'):
            #return wordnet.ADV
        #else:
            #return wordnet.NOUN
    
    #lemmatizer = WordNetLemmatizer()
    #lemmas = [lemmatizer.lemmatize(w, get_wordnet_pos(t)) for w, t in tagged]
    
    # 6. remove stopwords (LAST)
    #from nltk.corpus import stopwords
    #stop_words = set(stopwords.words('english'))
    #cleaned = [w for w in lemmas if w not in stop_words]
    
    #return ' '.join(cleaned)

In [23]:
df_merge.isnull().sum()

subject    260
body         0
label        0
dtype: int64

In [24]:
df_merge["subject_missing"] = df_merge["subject"].isnull()
df_merge[df_merge["subject_missing"] == True]



,subject,body,label,subject_missing
3517,NaN,the only fix to penis growth\r\nlimited time o...,1,True
3524,NaN,a permanent solution to penis growth\r\nlimite...,1,True
3540,NaN,a only fix to penis enlargement\r\nlimited tim...,1,True
3543,NaN,the only solution to penis growth\r\nlimited t...,1,True
3566,NaN,html\r\nbody\r\npbr\r\n/ p\r\np align = center...,1,True
...,...,...,...,...
32042,NaN,the latest issue ( 1994 n01 ) of etudes de let...,0,True
32055,NaN,b a r g a i n a i r f a r e s your 1 - stop tr...,1,True
32297,NaN,"data to : = 20 date : fri , 06 feb 1998 22 : 3...",1,True
32303,NaN,"epac . pt , e . carnoali @ genie . com , e . c...",1,True


In [25]:
df_merge["subject"] = df_merge["subject"].fillna("")

In [26]:
df_merge["subject"].isnull().sum()

np.int64(0)

In [27]:
import string
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english')) - {"not", "no", "nor"}

def preprocess(text):
    # lowercase
    text = text.lower()
    
    # remove punctuation
    text = ''.join(c for c in text if c not in string.punctuation)
    
    # simple tokenization (split)
    words = text.split()
    
    # remove stopwords
    words = [w for w in words if w not in stop_words]
    
    return ' '.join(words)

In [28]:
# 2. combine
df_merge["text"] = df_merge["subject"] + " " + df_merge["body"]

In [29]:
# 3. preprocess text
df_merge["clean_text"] = df_merge["text"].apply(preprocess)

In [30]:
df_merge.head()

,subject,body,label,subject_missing,text,clean_text
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0,False,"hpl nom for may 25 , 2001 ( see attached file ...",hpl nom may 25 2001 see attached file hplno 52...
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0,False,re : nom / actual vols for 24 th - - - - - - -...,nom actual vols 24 th forwarded sabrae zajac h...
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0,False,"enron actuals for march 30 - april 1 , 201 est...",enron actuals march 30 april 1 201 estimated a...
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0,False,"hpl nom for may 30 , 2001 ( see attached file ...",hpl nom may 30 2001 see attached file hplno 53...
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0,False,"hpl nom for june 1 , 2001 ( see attached file ...",hpl nom june 1 2001 see attached file hplno 60...


In [31]:
print(df_merge.shape)

(32626, 6)


In [32]:
df_3=pd.read_csv('CEAS_08.csv')
df_3.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1


In [33]:
df_4=pd.read_csv('Nazario.csv')
df_4.head()

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1


In [34]:
df_5=pd.read_csv('Nigerian_Fraud.csv')
df_5.head()

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1


In [35]:
df_6=pd.read_csv('SpamAssasin.csv')
df_6.head()

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1


In [36]:
print(df_3.shape)

(39154, 7)


In [37]:
print(df_4.shape)

(1565, 7)


In [38]:
print(df_5.shape)

(3332, 7)


In [39]:
print(df_6.shape)

(5809, 7)


In [40]:
# merge 4 dataframes df_3,df_4,df_5,df_6
df_merge_1= pd.concat([df_3, df_4, df_5, df_6], ignore_index=True)

In [41]:
df_merge_1.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1


In [42]:
print(df_merge_1.shape)

(49860, 7)


In [43]:
df_merge_1.isnull().sum()

sender       331
receiver    2092
date         483
subject       87
body           1
label          0
urls           0
dtype: int64

In [44]:
df_merge_1["subject"] = df_merge_1["subject"].fillna("")
df_merge_1["body"] = df_merge_1["body"].fillna("")


In [45]:
df_merge_1["sender"] = df_merge_1["sender"].fillna("unknown_sender")
df_merge_1["receiver"] = df_merge_1["receiver"].fillna("unknown_receiver")

In [46]:
df_merge_1.isnull().sum()

sender        0
receiver      0
date        483
subject       0
body          0
label         0
urls          0
dtype: int64

In [47]:
df_merge_1[df_merge_1["date"].isnull()]

,sender,receiver,date,subject,body,label,urls
39705,Please login to your Apple ID from \t\t\t\t...,unknown_receiver,NaN,"https://hurinet.or.ug/webapp/, ,",1,1,0
40725,Barrister tunde dosumu <tunde_dosumu@lycos.com>,unknown_receiver,NaN,Urgent Attention,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
40728,Tunde Dosumu <barrister_td@lycos.com>,unknown_receiver,NaN,Urgent Assistance,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
40738,unknown_sender,oshea@UM,NaN,WANTED FOR FRAUD: Fawwaz Ulaby,"$250,000 FOR INFORMATION:\n\nLEADING TO THE CR...",1,1
40742,edema_mb@phantomemail.com,edema_mb@phantomemail.com,NaN,BUSINESS RELATIONSHIP,FROM: Edema Martins.\nPlot 243 Walter Carringt...,1,1
...,...,...,...,...,...,...,...
44009,unknown_sender,stephen@it.usyd.edu.au,NaN,MES FELICITATIONS...,LOTERIE MONDIALE \n\n\n ...,1,0
44017,unknown_sender,onuoha5a2003@yahoo.co.jp,NaN,From:Miss Grace Onuoha,01 BP 1598 ABIDJAN 01 ...,1,0
44019,unknown_sender,resumes@collarini.com,NaN,INVESTMENT...,"Dear Friend,\n \n Please I would like to ap...",1,0
44032,unknown_sender,R@S,NaN,HOW WOULD YOU USE MY FUND TO HELP THE LESS PRI...,"It is a great honour to write you, after sever...",1,0


In [48]:
df_merge_1["date"] = pd.to_datetime(df_merge_1["date"], errors="coerce", utc=True)

In [49]:
df_merge_1["date"] = df_merge_1["date"].fillna("unknown")

In [50]:
df_merge_1["date"] = df_merge_1["date"].astype(str)

In [51]:
df_merge_1.isnull().sum()

sender      0
receiver    0
date        0
subject     0
body        0
label       0
urls        0
dtype: int64

In [52]:
# 2. combine
df_merge_1["text"] = df_merge_1["sender"]+" "+" "+ df_merge_1["date"]+" "+ df_merge_1["subject"] + " " + df_merge_1["body"]

In [53]:
# 3.preprocess text
df_merge_1["clean_text"] = df_merge_1["text"].apply(preprocess)

In [54]:
df_merge_1.head()

,sender,receiver,date,subject,body,label,urls,text,clean_text
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,2008-08-05 23:31:02+00:00,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1,Young Esposito <Young@iworld.de> 2008-08-05 2...,young esposito youngiworldde 20080805 23310200...
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,2008-08-05 23:31:03+00:00,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1,Mok <ipline's1983@icable.ph> 2008-08-05 23:31...,mok iplines1983icableph 20080805 2331030000 be...
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,2008-08-06 08:28:00+00:00,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1,Daily Top 10 <Karmandeep-opengevl@universalnet...,daily top 10 karmandeepopengevluniversalnetpsi...
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,2008-08-05 23:31:20+00:00,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1,Michael Parker <ivqrnai@pobox.com> 2008-08-05...,michael parker ivqrnaipoboxcom 20080805 233120...
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,2008-08-05 23:31:21+00:00,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1,Gretchen Suggs <externalsep1@loanofficertool.c...,gretchen suggs externalsep1loanofficertoolcom ...


In [55]:
print(df_merge_1.shape)

(49860, 9)


In [56]:
df_merge.head()

,subject,body,label,subject_missing,text,clean_text
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0,False,"hpl nom for may 25 , 2001 ( see attached file ...",hpl nom may 25 2001 see attached file hplno 52...
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0,False,re : nom / actual vols for 24 th - - - - - - -...,nom actual vols 24 th forwarded sabrae zajac h...
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0,False,"enron actuals for march 30 - april 1 , 201 est...",enron actuals march 30 april 1 201 estimated a...
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0,False,"hpl nom for may 30 , 2001 ( see attached file ...",hpl nom may 30 2001 see attached file hplno 53...
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0,False,"hpl nom for june 1 , 2001 ( see attached file ...",hpl nom june 1 2001 see attached file hplno 60...


In [57]:
df_merge_1[df_merge_1["date"].str.contains("unknown", na=False)].head()

,sender,receiver,date,subject,body,label,urls,text,clean_text
6279,msvksyhq@bodyandcolor.com,cstheory@gvc.ceas-challenge.cc,unknown,All that beach chicks,Summer is here \n\nhttp://lookresolution.com/?...,1,1,msvksyhq@bodyandcolor.com unknown All that be...,msvksyhqbodyandcolorcom unknown beach chicks s...
7410,mpghaoeq@blumhorst.com,cstheory@gvc.ceas-challenge.cc,unknown,Need no words,Need no words \n\nhttp://spivaka.cn/v/\n\n\n,1,1,mpghaoeq@blumhorst.com unknown Need no words ...,mpghaoeqblumhorstcom unknown need no words nee...
8611,rjjtryw@boxerproperty.com,cstheory@gvc.ceas-challenge.cc,unknown,Sunshine,Olympus mountain \n\nhttp://eitherindependence...,1,1,rjjtryw@boxerproperty.com unknown Sunshine Ol...,rjjtrywboxerpropertycom unknown sunshine olymp...
9600,qoaikmk@boltongrp.com,cstheory@gvc.ceas-challenge.cc,unknown,Beijing 2008,Olympic people \n\nhttp://eitherindependence.c...,1,1,qoaikmk@boltongrp.com unknown Beijing 2008 Ol...,qoaikmkboltongrpcom unknown beijing 2008 olymp...
12253,kywyeayhcmu@bosaship.com,cstheory@gvc.ceas-challenge.cc,unknown,Get hot,"Sun, sea and summer \n\nhttp://eitherindepende...",1,1,"kywyeayhcmu@bosaship.com unknown Get hot Sun,...",kywyeayhcmubosashipcom unknown get hot sun sea...


In [58]:
df_final = pd.concat([
    df_merge[["clean_text", "label"]],
    df_merge_1[["clean_text", "label"]]
], ignore_index=True)

In [59]:
print(df_final.shape)

(82486, 2)


In [60]:
df_final.head()

,clean_text,label
0,hpl nom may 25 2001 see attached file hplno 52...,0
1,nom actual vols 24 th forwarded sabrae zajac h...,0
2,enron actuals march 30 april 1 201 estimated a...,0
3,hpl nom may 30 2001 see attached file hplno 53...,0
4,hpl nom june 1 2001 see attached file hplno 60...,0


In [61]:
df_final["label"].value_counts()

label
1    42891
0    39595
Name: count, dtype: int64

# Train Test split

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_final["clean_text"], df_final["label"],
    test_size=0.2, random_state=42, #stratify=df_final["label"]
)

# tokenize text

In [63]:
X_train_tokens = X_train.apply(lambda x: x.split())
X_test_tokens = X_test.apply(lambda x: x.split())

# checking results of tokenize text 

In [64]:
print(X_train_tokens.head())

36471    [ezekiel, boleslaw, csvofreelernl, 20080806, 0...
7743     [fyi, new, esai, report, forecasting, power, p...
43256    [jan, vickers, jansihcomhk, 20080806, 15472200...
52280    [sebring, gentitetsggyocdmcleanorg, 20080807, ...
22663    [z, app, term, life, business, z, app, easy, f...
Name: clean_text, dtype: object


In [65]:
# check the first element in X_train and X_train_tokens
print(X_train.iloc[0])        # original text
print(X_train_tokens.iloc[0]) # tokenized version

ezekiel boleslaw csvofreelernl 20080806 0147010000 everybody wants looking cheap chemists wont find better solution site everything help recover ilnesseseven need fast delivery always trust us obtain experienced help fast mouse click traditionstreetcom 5 aug 2008 211532 3 sport
['ezekiel', 'boleslaw', 'csvofreelernl', '20080806', '0147010000', 'everybody', 'wants', 'looking', 'cheap', 'chemists', 'wont', 'find', 'better', 'solution', 'site', 'everything', 'help', 'recover', 'ilnesseseven', 'need', 'fast', 'delivery', 'always', 'trust', 'us', 'obtain', 'experienced', 'help', 'fast', 'mouse', 'click', 'traditionstreetcom', '5', 'aug', '2008', '211532', '3', 'sport']


In [66]:
#checking type of the first element in X_train_tokens
print(type(X_train_tokens.iloc[0]))

<class 'list'>


In [67]:
print(len(X_train_tokens.iloc[0]))

38


In [68]:
tokens_flat = [word for tokens in X_train_tokens for word in tokens]
print(set(tokens_flat[:50]))

{'new', 'fast', 'wont', 'attached', 'chemists', '0147010000', 'delivery', 'always', 'experienced', 'trust', 'mouse', 'aug', 'ezekiel', 'wants', '3', 'esai', 'better', '20080806', '5', '211532', 'report', 'site', 'obtain', 'traditionstreetcom', 'everybody', 'fyi', 'ilnesseseven', 'sport', 'everything', 'csvofreelernl', 'cheap', 'eastern', 'forecasting', 'find', 'us', 'need', 'boleslaw', 'prices', '2008', 'looking', 'solution', 'help', 'recover', 'click', 'markets', 'power'}


In [69]:
empty_docs = X_train_tokens[X_train_tokens.apply(len) == 0]
print(len(empty_docs))

# If > 0:
# Word2Vec may fail or give zero vectors

0


In [70]:
print(X_train_tokens.shape)
print(X_test_tokens.shape)

(65988,)
(16498,)


In [71]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
    --------------------------------------- 0.5/24.4 MB 1.3 MB/s eta 0:00:19
   - -------------------------------------- 1.0/24.4 MB 1.9 MB/s eta 0:00:13
   -- ------------------------------------- 1.6/24.4 MB 2.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.1/24.4 MB 2.2 MB/s eta 0:00:11
   ----- ---------------------------------- 3.1/24.4 MB 2.6 MB/s eta 0:00:09
   ------ --------------------------------- 3.7/24.4 MB 2.8 MB/s eta 0:00:08
   ------ --------------------------------- 4.2/24.4 MB 2.8 MB/s eta 0:00:08
   ------- -------------------------------- 4.5/24.4 MB 2.7 MB/s eta 0:00:08
   -------- ------------------------------- 5.2/24.4 MB 2.6 MB/s eta 0:00:08
   -------- ------------------------------- 5.2/24.4 MB 2.6 MB/s eta 0:00:08
   --------- ------------------------------ 5.8/24.4 MB 2.4 MB/s eta 0:00:08
   --------- 


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Train Word2Vec on training data

In [72]:
from gensim.models import Word2Vec
import numpy as np

# -----------------------------
# 1. Train Word2Vec on TRAIN set only
# -----------------------------
w2v_model = Word2Vec(
    sentences=X_train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,          # 1 = Skip-gram, 0 = CBOW
    seed=42
)

# -----------------------------
# 2. Function to convert one document into one vector
#    using average of word vectors
# -----------------------------
def document_vector(tokens, model):
    valid_vectors = [model.wv[word] for word in tokens if word in model.wv]
    
    if len(valid_vectors) == 0:
        return np.zeros(model.vector_size)
    
    return np.mean(valid_vectors, axis=0)

# -----------------------------
# 3. Convert all train and test documents
# -----------------------------
X_train_w2v = np.array([document_vector(tokens, w2v_model) for tokens in X_train_tokens])
X_test_w2v = np.array([document_vector(tokens, w2v_model) for tokens in X_test_tokens])

# -----------------------------
# 4. Sanity checks
# -----------------------------
print("Train Word2Vec shape:", X_train_w2v.shape)
print("Test Word2Vec shape:", X_test_w2v.shape)
print("Word2Vec vector size:", w2v_model.vector_size)
print("Vocabulary size:", len(w2v_model.wv))

# -----------------------------
# 5. Check how many documents became all-zero vectors
# -----------------------------
train_zero_docs = np.sum(np.all(X_train_w2v == 0, axis=1))
test_zero_docs = np.sum(np.all(X_test_w2v == 0, axis=1))

print("Zero-vector documents in train set:", train_zero_docs)
print("Zero-vector documents in test set:", test_zero_docs)

# -----------------------------
# 6. Optional: inspect one sample
# -----------------------------
print("\nExample tokens:")
print(X_train_tokens.iloc[0])

print("\nExample document vector (first 10 values):")
print(X_train_w2v[0][:10])

Train Word2Vec shape: (65988, 100)
Test Word2Vec shape: (16498, 100)
Word2Vec vector size: 100
Vocabulary size: 219739
Zero-vector documents in train set: 1
Zero-vector documents in test set: 1

Example tokens:
['ezekiel', 'boleslaw', 'csvofreelernl', '20080806', '0147010000', 'everybody', 'wants', 'looking', 'cheap', 'chemists', 'wont', 'find', 'better', 'solution', 'site', 'everything', 'help', 'recover', 'ilnesseseven', 'need', 'fast', 'delivery', 'always', 'trust', 'us', 'obtain', 'experienced', 'help', 'fast', 'mouse', 'click', 'traditionstreetcom', '5', 'aug', '2008', '211532', '3', 'sport']

Example document vector (first 10 values):
[-0.39690158 -0.01392301 -0.08103314 -0.25183916 -0.17316271 -0.121439
 -0.13822994 -0.16182475 -0.39569667  0.30813169]


In [73]:
zero_train_idx = np.where(np.all(X_train_w2v == 0, axis=1))[0]
print(X_train.iloc[zero_train_idx])

72987    utf8btm90awnl contactjmcpavicombr 20200618 003...
Name: clean_text, dtype: str


In [74]:
zero_text_idx = np.where(np.all(X_test_w2v == 0, axis=1))[0]
print(X_test.iloc[zero_text_idx])

4086    
Name: clean_text, dtype: str


# 1. Gaussian NB

In [75]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

# Train
gnb_model = GaussianNB()
gnb_model.fit(X_train_w2v, y_train)

# Predict
y_pred_nb_w2v = gnb_model.predict(X_test_w2v)

# Evaluate
print("Gaussian Naive Bayes + Word2Vec")
print(confusion_matrix(y_test, y_pred_nb_w2v))
print(classification_report(y_test, y_pred_nb_w2v))

Gaussian Naive Bayes + Word2Vec
[[7368  561]
 [2499 6070]]
              precision    recall  f1-score   support

           0       0.75      0.93      0.83      7929
           1       0.92      0.71      0.80      8569

    accuracy                           0.81     16498
   macro avg       0.83      0.82      0.81     16498
weighted avg       0.83      0.81      0.81     16498



# 2. Logistic Regression (Standard Scaling is required)

1.Baseline Logistic Regression with Word2Vec

In [76]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Scale Word2Vec features
scaler = StandardScaler()
X_train_w2v_scaled = scaler.fit_transform(X_train_w2v)
X_test_w2v_scaled = scaler.transform(X_test_w2v)

# Logistic Regression
lr_w2v = LogisticRegression(
    random_state=42,
    max_iter=5000
)

# Train
lr_w2v.fit(X_train_w2v_scaled, y_train)

# Predict
y_pred_lr_w2v = lr_w2v.predict(X_test_w2v_scaled)

# Evaluate
print("Logistic Regression + Scaled Word2Vec")
print(confusion_matrix(y_test, y_pred_lr_w2v))
print(classification_report(y_test, y_pred_lr_w2v))

Logistic Regression + Scaled Word2Vec
[[7677  252]
 [ 229 8340]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7929
           1       0.97      0.97      0.97      8569

    accuracy                           0.97     16498
   macro avg       0.97      0.97      0.97     16498
weighted avg       0.97      0.97      0.97     16498



2. Option A: tune standard Logistic Regression

In [77]:
#from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

# 1. Scale Word2Vec features
#scaler = StandardScaler()
#X_train_w2v_scaled = scaler.fit_transform(X_train_w2v)
#X_test_w2v_scaled = scaler.transform(X_test_w2v)

# 2. Parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['lbfgs', 'liblinear'],
    'class_weight': [None, 'balanced']
}

# 3. GridSearchCV
grid_lr_w2v = GridSearchCV(
    LogisticRegression(
        random_state=42,
        max_iter=5000
    ),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# 4. Train
grid_lr_w2v.fit(X_train_w2v_scaled, y_train)

# 5. Best result
print("Best parameters:", grid_lr_w2v.best_params_)
print("Best CV recall:", grid_lr_w2v.best_score_)

# 6. Full GridSearch results
df = pd.DataFrame(grid_lr_w2v.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['C', 'solver', 'class_weight',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)



Best parameters: {'C': 1, 'class_weight': None, 'solver': 'liblinear'}
Best CV recall: 0.9751762870174723

All parameter combinations:
        C     solver class_weight  mean_train_score  mean_test_score  \
9    1.00  liblinear          NaN          0.976065         0.975176   
8    1.00      lbfgs          NaN          0.975963         0.975118   
13  10.00  liblinear          NaN          0.976094         0.975089   
12  10.00      lbfgs          NaN          0.975992         0.975089   
5    0.10  liblinear          NaN          0.975992         0.975060   
0    0.01      lbfgs          NaN          0.975774         0.974943   
4    0.10      lbfgs          NaN          0.975963         0.974914   
1    0.01  liblinear          NaN          0.975322         0.974302   
15  10.00  liblinear     balanced          0.974550         0.973399   
11   1.00  liblinear     balanced          0.974535         0.973370   
2    0.01      lbfgs     balanced          0.973923         0.973341   
1

In [78]:
# 7. Test best model
best_lr_w2v = grid_lr_w2v.best_estimator_
y_pred_best_lr_w2v = best_lr_w2v.predict(X_test_w2v_scaled)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_lr_w2v))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_lr_w2v))


Confusion Matrix:
[[7680  249]
 [ 230 8339]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7929
           1       0.97      0.97      0.97      8569

    accuracy                           0.97     16498
   macro avg       0.97      0.97      0.97     16498
weighted avg       0.97      0.97      0.97     16498



3. Option B: tune Elastic Net Logistic Regression

In [79]:

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

# 2. Parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.2, 0.5, 0.8],
    'class_weight': [None, 'balanced']
}

# 3. GridSearchCV
grid_lr_en_w2v = GridSearchCV(
    LogisticRegression(
        penalty='elasticnet',
        solver='saga',
        random_state=42,
        max_iter=5000
    ),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# 4. Train
grid_lr_en_w2v.fit(X_train_w2v_scaled, y_train)

# 5. Best result
print("Best parameters:", grid_lr_en_w2v.best_params_)
print("Best CV recall:", grid_lr_en_w2v.best_score_)

# 6. Full GridSearch results
df = pd.DataFrame(grid_lr_en_w2v.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['C', 'l1_ratio', 'class_weight',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)



d:\2. Cyber Security\Term Project\New folder\cybersec_1\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(


Best parameters: {'C': 0.1, 'class_weight': None, 'l1_ratio': 0.8}
Best CV recall: 0.9752928294937298

All parameter combinations:
        C  l1_ratio class_weight  mean_train_score  mean_test_score  \
8    0.10       0.8          NaN          0.976123         0.975293   
7    0.10       0.5          NaN          0.976007         0.975264   
6    0.10       0.2          NaN          0.976007         0.975176   
20  10.00       0.8          NaN          0.976094         0.975147   
12   1.00       0.2          NaN          0.976065         0.975147   
19  10.00       0.5          NaN          0.976094         0.975118   
18  10.00       0.2          NaN          0.976094         0.975118   
14   1.00       0.8          NaN          0.976050         0.975118   
13   1.00       0.5          NaN          0.976065         0.975089   
0    0.01       0.2          NaN          0.975468         0.974827   
1    0.01       0.5          NaN          0.974812         0.974186   
11   0.10       0

In [80]:
# 7. Test best model
best_lr_en_w2v = grid_lr_en_w2v.best_estimator_
y_pred_best_lr_en_w2v = best_lr_en_w2v.predict(X_test_w2v_scaled)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_lr_en_w2v))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_lr_en_w2v))


Confusion Matrix:
[[7681  248]
 [ 231 8338]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7929
           1       0.97      0.97      0.97      8569

    accuracy                           0.97     16498
   macro avg       0.97      0.97      0.97     16498
weighted avg       0.97      0.97      0.97     16498



# 3. Linear SVC (standard scaling is done above.)

In [81]:
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, classification_report

# Baseline model
svc_w2v = LinearSVC(
    random_state=42,
    max_iter=5000
)

# Train
svc_w2v.fit(X_train_w2v_scaled, y_train)

# Predict
y_pred_svc_w2v = svc_w2v.predict(X_test_w2v_scaled)

# Evaluate
print("Linear SVC + Word2Vec")
print(confusion_matrix(y_test, y_pred_svc_w2v))
print(classification_report(y_test, y_pred_svc_w2v))

Linear SVC + Word2Vec
[[7669  260]
 [ 224 8345]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7929
           1       0.97      0.97      0.97      8569

    accuracy                           0.97     16498
   macro avg       0.97      0.97      0.97     16498
weighted avg       0.97      0.97      0.97     16498



In [82]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'class_weight': [None, 'balanced']
}

grid_svc_w2v = GridSearchCV(
    LinearSVC(
        random_state=42,
        max_iter=5000
    ),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_svc_w2v.fit(X_train_w2v_scaled, y_train)

# Best result
print("Best parameters:", grid_svc_w2v.best_params_)
print("Best CV recall:", grid_svc_w2v.best_score_)

# Full results
df = pd.DataFrame(grid_svc_w2v.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['C', 'class_weight',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)



Best parameters: {'C': 0.01, 'class_weight': None}
Best CV recall: 0.9757589841181747

All parameter combinations:
       C class_weight  mean_train_score  mean_test_score  rank_test_score
0   0.01          NaN          0.976327         0.975759                1
2   0.10          NaN          0.976298         0.975584                2
6  10.00          NaN          0.976313         0.975584                2
4   1.00          NaN          0.976298         0.975584                2
3   0.10     balanced          0.974943         0.974448                5
1   0.01     balanced          0.974914         0.974419                6
5   1.00     balanced          0.974972         0.974360                7
7  10.00     balanced          0.974972         0.974360                7


In [83]:
# Test best model
best_svc_w2v = grid_svc_w2v.best_estimator_
y_pred_best_svc_w2v = best_svc_w2v.predict(X_test_w2v_scaled)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_svc_w2v))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_svc_w2v))


Confusion Matrix:
[[7670  259]
 [ 221 8348]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7929
           1       0.97      0.97      0.97      8569

    accuracy                           0.97     16498
   macro avg       0.97      0.97      0.97     16498
weighted avg       0.97      0.97      0.97     16498



# 4. Random Forest (do not use Scaled Trained & Test set)

In [84]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

rf_w2v = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

# Train
rf_w2v.fit(X_train_w2v, y_train)

# Predict
y_pred_rf_w2v = rf_w2v.predict(X_test_w2v)

# Evaluate
print("Random Forest + Word2Vec")
print(confusion_matrix(y_test, y_pred_rf_w2v))
print(classification_report(y_test, y_pred_rf_w2v))

Random Forest + Word2Vec
[[7770  159]
 [ 122 8447]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7929
           1       0.98      0.99      0.98      8569

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498



In [85]:
from sklearn.model_selection import GridSearchCV
import pandas as pd

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_rf_w2v = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_rf_w2v.fit(X_train_w2v, y_train)

# Best result
print("Best parameters:", grid_rf_w2v.best_params_)
print("Best CV recall:", grid_rf_w2v.best_score_)



# Full results
df = pd.DataFrame(grid_rf_w2v.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['n_estimators', 'max_depth', 'min_samples_split', 'min_samples_leaf',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)


Best parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Best CV recall: 0.9853446912904129

All parameter combinations:
    n_estimators  max_depth  min_samples_split  min_samples_leaf  \
3            200        NaN                  5                 1   
7            200        NaN                  5                 2   
6            100        NaN                  5                 2   
11           200       20.0                  5                 1   
13           200       20.0                  2                 2   
0            100        NaN                  2                 1   
8            100       20.0                  2                 1   
4            100        NaN                  2                 2   
12           100       20.0                  2                 2   
2            100        NaN                  5                 1   
5            200        NaN                  2                 2   
1            20

In [86]:
# Test best model
best_rf_w2v = grid_rf_w2v.best_estimator_
y_pred_best_rf_w2v = best_rf_w2v.predict(X_test_w2v)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_rf_w2v))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_rf_w2v))


Confusion Matrix:
[[7781  148]
 [ 114 8455]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      7929
           1       0.98      0.99      0.98      8569

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498



# 5. Decision Tree (do not use standard scaling)

In [87]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

dt_w2v = DecisionTreeClassifier(
    random_state=42
)

# Train
dt_w2v.fit(X_train_w2v, y_train)

# Predict
y_pred_dt_w2v = dt_w2v.predict(X_test_w2v)

# Evaluate
print("Decision Tree + Word2Vec")
print(confusion_matrix(y_test, y_pred_dt_w2v))
print(classification_report(y_test, y_pred_dt_w2v))

Decision Tree + Word2Vec
[[7507  422]
 [ 410 8159]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      7929
           1       0.95      0.95      0.95      8569

    accuracy                           0.95     16498
   macro avg       0.95      0.95      0.95     16498
weighted avg       0.95      0.95      0.95     16498



In [88]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

param_grid = {
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_dt_w2v = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_dt_w2v.fit(X_train_w2v, y_train)

# Best result
print("Best parameters:", grid_dt_w2v.best_params_)
print("Best CV recall:", grid_dt_w2v.best_score_)

# Full results
df = pd.DataFrame(grid_dt_w2v.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['max_depth', 'min_samples_split', 'min_samples_leaf',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)



Best parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best CV recall: 0.9507896675331776

All parameter combinations:
    max_depth  min_samples_split  min_samples_leaf  mean_train_score  \
4        20.0                  2                 1          0.996373   
5        20.0                  5                 1          0.993692   
8         NaN                  2                 1          1.000000   
9         NaN                  5                 1          0.996649   
0        10.0                  2                 1          0.968694   
1        10.0                  5                 1          0.968315   
7        20.0                  5                 2          0.986933   
6        20.0                  2                 2          0.987646   
3        10.0                  5                 2          0.966538   
10        NaN                  2                 2          0.988972   
2        10.0                  2                 2          0.

In [89]:
# Test best model
best_dt_w2v = grid_dt_w2v.best_estimator_
y_pred_best_dt_w2v = best_dt_w2v.predict(X_test_w2v)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_dt_w2v))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_dt_w2v))


Confusion Matrix:
[[7565  364]
 [ 413 8156]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      7929
           1       0.96      0.95      0.95      8569

    accuracy                           0.95     16498
   macro avg       0.95      0.95      0.95     16498
weighted avg       0.95      0.95      0.95     16498



# Model Comparison (Guassian Naive Bayes, Linear SVC, Random Forest, Decision Tree, Logistic Regression)

In [90]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd

# Put Word2Vec model names and predictions here
model_predictions_w2v = {
    'Gaussian Naive Bayes': y_pred_nb_w2v,
    'Logistic Regression': y_pred_best_lr_en_w2v,
    'Random Forest': y_pred_best_rf_w2v,
    'Decision Tree': y_pred_best_dt_w2v,
    'Linear SVC': y_pred_best_svc_w2v
}

results_w2v = []

for model_name, y_pred in model_predictions_w2v.items():
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    
    results_w2v.append({
        'Model': model_name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision (Class 1)': precision_score(y_test, y_pred, pos_label=1),
        'Recall (Class 1)': recall_score(y_test, y_pred, pos_label=1),
        'F1-score (Class 1)': f1_score(y_test, y_pred, pos_label=1),
        'False Positives': fp,
        'False Negatives': fn
    })

comparison_w2v_df = pd.DataFrame(results_w2v)
comparison_w2v_df = comparison_w2v_df.sort_values(by='Recall (Class 1)', ascending=False)
comparison_w2v_df = comparison_w2v_df.round(2)

print(comparison_w2v_df)

                  Model  Accuracy  Precision (Class 1)  Recall (Class 1)  \
2         Random Forest      0.98                 0.98              0.99   
4            Linear SVC      0.97                 0.97              0.97   
1   Logistic Regression      0.97                 0.97              0.97   
3         Decision Tree      0.95                 0.96              0.95   
0  Gaussian Naive Bayes      0.81                 0.92              0.71   

   F1-score (Class 1)  False Positives  False Negatives  
2                0.98              148              114  
4                0.97              259              221  
1                0.97              248              231  
3                0.95              364              413  
0                0.80              561             2499  


In [91]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

class Word2VecTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, w2v_model):
        self.w2v_model = w2v_model
        self.vector_size = w2v_model.vector_size

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return np.array([self.document_vector(text) for text in X])

    def document_vector(self, text):
        tokens = text.lower().split()
        vectors = [self.w2v_model.wv[word] for word in tokens if word in self.w2v_model.wv]

        if len(vectors) == 0:
            return np.zeros(self.vector_size)

        return np.mean(vectors, axis=0)

In [92]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

w2v_transformer = Word2VecTransformer(w2v_model)

pipeline_w2v_rf = Pipeline([
    ('w2v', w2v_transformer),
    ('rf', RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        min_samples_split=5,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    ))
])

pipeline_w2v_rf.fit(X_train, y_train)
import pickle

with open("w2v_rf_pipeline.pkl", "wb") as f:
    pickle.dump(pipeline_w2v_rf, f)

In [93]:
with open("w2v_rf_pipeline.pkl", "rb") as f:
    model = pickle.load(f)

y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7778  151]
 [ 119 8450]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7929
           1       0.98      0.99      0.98      8569

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498



# Test with Real Text

In [94]:
new_text = ["free money now click here"]

prediction = model.predict(new_text)

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Label: Phishing


In [95]:
samples = [
    "meeting scheduled tomorrow",
    "urgent click this link now",
    "your bank account is safe",
    "win free prize now"
]

preds = model.predict(samples)

for text, pred in zip(samples, preds):
    label = "Phishing" if pred == 1 else "Legitimate"
    print(f"{text} → {label}")

meeting scheduled tomorrow → Legitimate
urgent click this link now → Phishing
your bank account is safe → Phishing
win free prize now → Phishing


In [96]:
example_text = ["""
dear customer your natwest online information has been flagged for routine check and this requires your attention
as part of our new security system we will be screening activity in the natwest system
we recently contacted you after noticing an issue on your account
we requested information from you for some reason
click here to continue
member services learn more about natwest online system
"""]

prediction = model.predict(example_text)

print("Prediction:", prediction[0])

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Prediction: 1
Label: Phishing
